# Change these first
owner: contratosapp # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: API
    url: https://enterprise.api.trato.io/health
  - name: clm
    url: https://clm.trato.io/login
  - name: starter
    url: https://starter.trato.io/v2/auth/login
assignees: # Users to assign downtime issues (optional)
  - gerardorochin
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.trato.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/contratosapp/upptime/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/contratosapp/upptime/master/assets/favicon.ico
  name: ""
  introTitle: "**Estado** de nuestros servicios."
  introMessage: Página de estado que utiliza datos en tiempo real de nuestra infraestructura, aquí encontrarás el estado operacional nuestros servicios.
  navbar:
    - title: Status
      href: /
    - title: Trato
      href: https://trato.io
    - title: Blog
      href: https://blog.trato.io
i18n:
  footer: ""
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
